---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: upg-loadme
  namespace: my-eks-201
  labels:
    app: upg-loadme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upg-loadme
  template:
    metadata:
      name: upg-loadme
      labels:
        app: upg-loadme
    spec:
      containers:
        - name: upg-loadme
          # update image id (manual or via jenkins)
          image: '353712235357.dkr.ecr.us-east-1.amazonaws.com/loadme-app:latest'
          # limiting cpu & mem usage of a pod
          resources:
            requests:
              cpu: 800m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 400Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      # add tolerations to restrict running on selected nodes
                    
      tolerations:
      - key: "appname"
        operator: "Equal"
        value: "loadme"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: appname
                operator: In
                values:
                - loadme

---
kind: Service
apiVersion: v1
metadata:
  name: upg-loadme
  namespace: my-eks-201
spec:
  selector:
    app: upg-loadme
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 8081